[tool.black]
line-length = 79
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
  ^/venv
  | migrations
  | infra_project/infra_project/settings.py
  | .eggs
  | .git
  | .hg
  | .mypy_cache
  | .tox
  | .venv
  | venv
  | __init__.py
  | _build
  | buck-out
  | build
  | dist
  | Dockerfile
)/
'''

[tool.isort]
atomic = true
profile = "black"
line_length = 79
skip_gitignore = true
skip_glob = ["src/blib2to3", "tests/data", "profiling"]
known_first_party = ["black", "blib2to3", "blackd", "_black_version"]