name: Django-app workflow

on: [push]

jobs:
  tests:
    # «Раннер» — создание изолированного окружения с последней версией Ubuntu
    runs-on: ubuntu-latest
    steps:
    # Запуск actions checkout — готового скрипта
    # для клонирования репозитория
    - uses: actions/checkout@v3
    - name: Set up Python
      # Запуск actions setup-python — готового скрипта
      # для развёртывания окружения Python
      uses: actions/setup-python@v4
      with:
        # Выбор версии Python
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        # обновление pip 
        python -m pip install --upgrade pip
        # установка зависимостей
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check lint with Black
      run: |
        # запуск проверки проекта c Black
        black --check .
    - name: Test with flake8 and django tests
      run: |
        # запуск проверки проекта по flake8
        python -m flake8
