name: Django-app workflow

on: [push]

jobs:
  formatting_and_tests:
    # «Раннер» — создание изолированного окружения с последней версией Ubuntu
    runs-on: ubuntu-latest
    steps:
    # Запуск actions checkout — готового скрипта
    # для клонирования репозитория
    - uses: actions/checkout@v3
    - name: Set up Python
      # Запуск actions setup-python — готового скрипта
      # для развёртывания окружения Python
      uses: actions/setup-python@v4
      with:
        # Выбор версии Python
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        # обновление pip 
        python -m pip install --upgrade pip
        # установка зависимостей
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check lint with Black
      run: |
        # запуск проверки проекта c Black
        black --check --diff .
    - name: Test with flake8
      run: |
        # запуск проверки проекта по flake8
        python -m flake8
    - name: Test django tests
      run: |
        # перейти в папку, содержащую manage.py
        cd infra_project/
        # запустить тесты
        python manage.py test
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: formatting_and_tests
    steps:
      - name: Check out the repo
        # Проверка доступности репозитория Docker Hub для workflow
        uses: actions/checkout@v3 
      - name: Set up Docker Buildx
        # Вызов сборщика контейнеров docker
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        # Запуск скрипта авторизации на Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        # Пуш образа в Docker Hub 
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/infra_project:latest 

